[2024-09-10T23:20:30.501+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-10T23:20:34.349+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Dag_Non-numeric-Quantity.run_anomaly_detection scheduled__2024-09-10T23:15:00+00:00 [queued]>
[2024-09-10T23:20:34.540+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Dag_Non-numeric-Quantity.run_anomaly_detection scheduled__2024-09-10T23:15:00+00:00 [queued]>
[2024-09-10T23:20:34.554+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-10T23:20:35.060+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_anomaly_detection> on 2024-09-10 23:15:00+00:00
[2024-09-10T23:20:35.317+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Dag_Non-numeric-Quantity', 'run_anomaly_detection', 'scheduled__2024-09-10T23:15:00+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/Dag_Non-numeric-Quantity.py', '--cfg-path', '/tmp/tmph7x07y03']
[2024-09-10T23:20:35.617+0000] {standard_task_runner.py:105} INFO - Job 118: Subtask run_anomaly_detection
[2024-09-10T23:20:35.725+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=714) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-10T23:20:35.734+0000] {standard_task_runner.py:72} INFO - Started process 771 to run task
[2024-09-10T23:20:39.661+0000] {task_command.py:467} INFO - Running <TaskInstance: Dag_Non-numeric-Quantity.run_anomaly_detection scheduled__2024-09-10T23:15:00+00:00 [running]> on host 5cd9362923f6
[2024-09-10T23:20:41.468+0000] {job.py:229} INFO - Heartbeat recovered after 16.86 seconds
[2024-09-10T23:20:41.930+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Dag_Non-numeric-Quantity' AIRFLOW_CTX_TASK_ID='run_anomaly_detection' AIRFLOW_CTX_EXECUTION_DATE='2024-09-10T23:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-10T23:15:00+00:00'
[2024-09-10T23:20:41.945+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-10T23:20:42.092+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-10T23:20:42.537+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-10T23:20:42.539+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Dag_Non-numeric-Quantity, task_id=run_anomaly_detection, run_id=scheduled__2024-09-10T23:15:00+00:00, execution_date=20240910T231500, start_date=20240910T232034, end_date=20240910T232042
[2024-09-10T23:20:43.227+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-10T23:20:43.901+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-10T23:20:43.917+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
