[2024-09-13T14:06:08.331+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-13T14:06:09.160+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Dag_NegativeQuantity_andTotalAmount.run_anomaly_detection scheduled__2024-09-13T13:55:00+00:00 [queued]>
[2024-09-13T14:06:09.302+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Dag_NegativeQuantity_andTotalAmount.run_anomaly_detection scheduled__2024-09-13T13:55:00+00:00 [queued]>
[2024-09-13T14:06:09.304+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-09-13T14:06:09.379+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_anomaly_detection> on 2024-09-13 13:55:00+00:00
[2024-09-13T14:06:09.551+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=99279) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-13T14:06:09.556+0000] {standard_task_runner.py:72} INFO - Started process 99318 to run task
[2024-09-13T14:06:09.578+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Dag_NegativeQuantity_andTotalAmount', 'run_anomaly_detection', 'scheduled__2024-09-13T13:55:00+00:00', '--job-id', '2426', '--raw', '--subdir', 'DAGS_FOLDER/Dag_NegativeQuantity_andTotalAmount.py', '--cfg-path', '/tmp/tmphnu0r12h']
[2024-09-13T14:06:09.584+0000] {standard_task_runner.py:105} INFO - Job 2426: Subtask run_anomaly_detection
[2024-09-13T14:06:11.624+0000] {task_command.py:467} INFO - Running <TaskInstance: Dag_NegativeQuantity_andTotalAmount.run_anomaly_detection scheduled__2024-09-13T13:55:00+00:00 [running]> on host 7403e816bcf5
[2024-09-13T14:06:13.254+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Dag_NegativeQuantity_andTotalAmount' AIRFLOW_CTX_TASK_ID='run_anomaly_detection' AIRFLOW_CTX_EXECUTION_DATE='2024-09-13T13:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-13T13:55:00+00:00'
[2024-09-13T14:06:13.258+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-13T14:06:14.105+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-13T14:06:14.475+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-13T14:06:14.477+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Dag_NegativeQuantity_andTotalAmount, task_id=run_anomaly_detection, run_id=scheduled__2024-09-13T13:55:00+00:00, execution_date=20240913T135500, start_date=20240913T140609, end_date=20240913T140614
[2024-09-13T14:06:14.593+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-13T14:06:14.897+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
