[2024-09-10T12:30:22.762+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-10T12:30:35.551+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: correction_Dag_Negative_Value.correct_negative_values scheduled__2024-09-10T12:25:00+00:00 [queued]>
[2024-09-10T12:30:35.880+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: correction_Dag_Negative_Value.correct_negative_values scheduled__2024-09-10T12:25:00+00:00 [queued]>
[2024-09-10T12:30:35.889+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-10T12:30:36.149+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): correct_negative_values> on 2024-09-10 12:25:00+00:00
[2024-09-10T12:30:38.473+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'correction_Dag_Negative_Value', 'correct_negative_values', 'scheduled__2024-09-10T12:25:00+00:00', '--job-id', '2184', '--raw', '--subdir', 'DAGS_FOLDER/Correction_dag_Negative_Value.py', '--cfg-path', '/tmp/tmprk42r5wm']
[2024-09-10T12:30:38.724+0000] {standard_task_runner.py:105} INFO - Job 2184: Subtask correct_negative_values
[2024-09-10T12:30:38.859+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6291) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-10T12:30:38.863+0000] {standard_task_runner.py:72} INFO - Started process 6327 to run task
[2024-09-10T12:30:46.265+0000] {job.py:229} INFO - Heartbeat recovered after 33.02 seconds
[2024-09-10T12:30:47.225+0000] {task_command.py:467} INFO - Running <TaskInstance: correction_Dag_Negative_Value.correct_negative_values scheduled__2024-09-10T12:25:00+00:00 [running]> on host 6d70a6e2c42a
[2024-09-10T12:30:51.300+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='correction_Dag_Negative_Value' AIRFLOW_CTX_TASK_ID='correct_negative_values' AIRFLOW_CTX_EXECUTION_DATE='2024-09-10T12:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-10T12:25:00+00:00'
[2024-09-10T12:30:51.318+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-10T12:30:52.023+0000] {logging_mixin.py:190} INFO - Anomalies corrigées avec succès.
[2024-09-10T12:30:52.026+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-10T12:30:52.497+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-10T12:30:52.502+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=correction_Dag_Negative_Value, task_id=correct_negative_values, run_id=scheduled__2024-09-10T12:25:00+00:00, execution_date=20240910T122500, start_date=20240910T123035, end_date=20240910T123052
[2024-09-10T12:30:52.798+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-10T12:30:53.337+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
