[2024-09-10T22:24:46.578+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-10T22:24:46.725+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: detect_1fn_anomalies_dag.detect_1nf_and_insert_anomalies manual__2024-09-10T22:24:41.630343+00:00 [queued]>
[2024-09-10T22:24:46.739+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: detect_1fn_anomalies_dag.detect_1nf_and_insert_anomalies manual__2024-09-10T22:24:41.630343+00:00 [queued]>
[2024-09-10T22:24:46.740+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-10T22:24:46.767+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): detect_1nf_and_insert_anomalies> on 2024-09-10 22:24:41.630343+00:00
[2024-09-10T22:24:46.785+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'detect_1fn_anomalies_dag', 'detect_1nf_and_insert_anomalies', 'manual__2024-09-10T22:24:41.630343+00:00', '--job-id', '3728', '--raw', '--subdir', 'DAGS_FOLDER/Dag_detect_1FN_anomaly.py', '--cfg-path', '/tmp/tmpsftdbvkx']
[2024-09-10T22:24:46.790+0000] {standard_task_runner.py:105} INFO - Job 3728: Subtask detect_1nf_and_insert_anomalies
[2024-09-10T22:24:46.793+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=854) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-10T22:24:46.794+0000] {standard_task_runner.py:72} INFO - Started process 868 to run task
[2024-09-10T22:24:47.352+0000] {task_command.py:467} INFO - Running <TaskInstance: detect_1fn_anomalies_dag.detect_1nf_and_insert_anomalies manual__2024-09-10T22:24:41.630343+00:00 [running]> on host f0946a6cef1f
[2024-09-10T22:24:47.852+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='detect_1fn_anomalies_dag' AIRFLOW_CTX_TASK_ID='detect_1nf_and_insert_anomalies' AIRFLOW_CTX_EXECUTION_DATE='2024-09-10T22:24:41.630343+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-10T22:24:41.630343+00:00'
[2024-09-10T22:24:47.853+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-10T22:24:47.893+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-10T22:24:47.993+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-10T22:24:47.994+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=detect_1fn_anomalies_dag, task_id=detect_1nf_and_insert_anomalies, run_id=manual__2024-09-10T22:24:41.630343+00:00, execution_date=20240910T222441, start_date=20240910T222446, end_date=20240910T222447
[2024-09-10T22:24:48.057+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-10T22:24:48.243+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-10T22:24:48.247+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
