[2024-09-22T16:00:54.680+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-22T16:00:56.896+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: welcome_dag.print_date scheduled__2024-09-22T15:00:59+00:00 [queued]>
[2024-09-22T16:00:56.965+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: welcome_dag.print_date scheduled__2024-09-22T15:00:59+00:00 [queued]>
[2024-09-22T16:00:56.967+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-22T16:00:57.425+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): print_date> on 2024-09-22 15:00:59+00:00
[2024-09-22T16:00:57.548+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'welcome_dag', 'print_date', 'scheduled__2024-09-22T15:00:59+00:00', '--job-id', '5281', '--raw', '--subdir', 'DAGS_FOLDER/Awelcome_dags.py', '--cfg-path', '/tmp/tmpq_8tshvz']
[2024-09-22T16:00:57.566+0000] {standard_task_runner.py:105} INFO - Job 5281: Subtask print_date
[2024-09-22T16:00:57.664+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=14155) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-22T16:00:57.685+0000] {standard_task_runner.py:72} INFO - Started process 14177 to run task
[2024-09-22T16:01:01.465+0000] {task_command.py:467} INFO - Running <TaskInstance: welcome_dag.print_date scheduled__2024-09-22T15:00:59+00:00 [running]> on host 93b0c38322b3
[2024-09-22T16:01:03.892+0000] {job.py:229} INFO - Heartbeat recovered after 15.43 seconds
[2024-09-22T16:01:06.057+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='welcome_dag' AIRFLOW_CTX_TASK_ID='print_date' AIRFLOW_CTX_EXECUTION_DATE='2024-09-22T15:00:59+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-22T15:00:59+00:00'
[2024-09-22T16:01:06.072+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-22T16:01:06.132+0000] {logging_mixin.py:190} INFO - Today is 2024-09-22
[2024-09-22T16:01:06.134+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-22T16:01:06.862+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-22T16:01:06.864+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=welcome_dag, task_id=print_date, run_id=scheduled__2024-09-22T15:00:59+00:00, execution_date=20240922T150059, start_date=20240922T160056, end_date=20240922T160106
[2024-09-22T16:01:07.111+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-22T16:01:07.729+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-09-22T16:01:08.076+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-22T16:01:08.090+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
