[2024-09-13T17:10:06.374+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-13T17:10:08.590+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Correction_dag_high_total_amount.Correction_dag_high_total_amount scheduled__2024-09-13T17:05:00+00:00 [queued]>
[2024-09-13T17:10:08.803+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Correction_dag_high_total_amount.Correction_dag_high_total_amount scheduled__2024-09-13T17:05:00+00:00 [queued]>
[2024-09-13T17:10:08.806+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-13T17:10:09.337+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): Correction_dag_high_total_amount> on 2024-09-13 17:05:00+00:00
[2024-09-13T17:10:10.298+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Correction_dag_high_total_amount', 'Correction_dag_high_total_amount', 'scheduled__2024-09-13T17:05:00+00:00', '--job-id', '2928', '--raw', '--subdir', 'DAGS_FOLDER/Correction_dag_high_total_amount.py', '--cfg-path', '/tmp/tmpd14i_mm4']
[2024-09-13T17:10:10.593+0000] {standard_task_runner.py:105} INFO - Job 2928: Subtask Correction_dag_high_total_amount
[2024-09-13T17:10:10.683+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=28835) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-13T17:10:10.697+0000] {standard_task_runner.py:72} INFO - Started process 28863 to run task
[2024-09-13T17:10:16.030+0000] {task_command.py:467} INFO - Running <TaskInstance: Correction_dag_high_total_amount.Correction_dag_high_total_amount scheduled__2024-09-13T17:05:00+00:00 [running]> on host 7403e816bcf5
[2024-09-13T17:10:17.026+0000] {job.py:229} INFO - Heartbeat recovered after 14.64 seconds
[2024-09-13T17:10:20.760+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Correction_dag_high_total_amount' AIRFLOW_CTX_TASK_ID='Correction_dag_high_total_amount' AIRFLOW_CTX_EXECUTION_DATE='2024-09-13T17:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-13T17:05:00+00:00'
[2024-09-13T17:10:20.812+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-13T17:10:21.212+0000] {logging_mixin.py:190} INFO - Les anomalies ont été corrigées dans la base de données.
[2024-09-13T17:10:21.223+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-13T17:10:22.216+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-13T17:10:22.222+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Correction_dag_high_total_amount, task_id=Correction_dag_high_total_amount, run_id=scheduled__2024-09-13T17:05:00+00:00, execution_date=20240913T170500, start_date=20240913T171008, end_date=20240913T171022
[2024-09-13T17:10:22.331+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-13T17:10:23.526+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
