[2024-10-23T12:37:38.723+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-23T12:37:38.941+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Dag_Non-numeric-Quantity.run_anomaly_detection scheduled__2024-10-23T12:25:00+00:00 [queued]>
[2024-10-23T12:37:38.978+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Dag_Non-numeric-Quantity.run_anomaly_detection scheduled__2024-10-23T12:25:00+00:00 [queued]>
[2024-10-23T12:37:38.979+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-23T12:37:39.032+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_anomaly_detection> on 2024-10-23 12:25:00+00:00
[2024-10-23T12:37:39.093+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=7343) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-23T12:37:39.096+0000] {standard_task_runner.py:72} INFO - Started process 7448 to run task
[2024-10-23T12:37:39.100+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Dag_Non-numeric-Quantity', 'run_anomaly_detection', 'scheduled__2024-10-23T12:25:00+00:00', '--job-id', '6164', '--raw', '--subdir', 'DAGS_FOLDER/Dag_Non-numeric-Quantity.py', '--cfg-path', '/tmp/tmph6z7nmit']
[2024-10-23T12:37:39.110+0000] {standard_task_runner.py:105} INFO - Job 6164: Subtask run_anomaly_detection
[2024-10-23T12:37:39.754+0000] {task_command.py:467} INFO - Running <TaskInstance: Dag_Non-numeric-Quantity.run_anomaly_detection scheduled__2024-10-23T12:25:00+00:00 [running]> on host 696ca67245ce
[2024-10-23T12:37:40.398+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Dag_Non-numeric-Quantity' AIRFLOW_CTX_TASK_ID='run_anomaly_detection' AIRFLOW_CTX_EXECUTION_DATE='2024-10-23T12:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-23T12:25:00+00:00'
[2024-10-23T12:37:40.403+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-23T12:37:40.632+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-23T12:37:40.865+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-23T12:37:40.866+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Dag_Non-numeric-Quantity, task_id=run_anomaly_detection, run_id=scheduled__2024-10-23T12:25:00+00:00, execution_date=20241023T122500, start_date=20241023T123738, end_date=20241023T123740
[2024-10-23T12:37:40.950+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-23T12:37:41.117+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
