[2024-09-11T13:20:22.059+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-11T13:20:22.647+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: detect_transaction_date_anomalies_dag.run_anomaly_detection scheduled__2024-09-11T13:15:00+00:00 [queued]>
[2024-09-11T13:20:22.688+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: detect_transaction_date_anomalies_dag.run_anomaly_detection scheduled__2024-09-11T13:15:00+00:00 [queued]>
[2024-09-11T13:20:22.691+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-11T13:20:22.757+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_anomaly_detection> on 2024-09-11 13:15:00+00:00
[2024-09-11T13:20:22.801+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=665) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-11T13:20:22.805+0000] {standard_task_runner.py:72} INFO - Started process 720 to run task
[2024-09-11T13:20:22.807+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'detect_transaction_date_anomalies_dag', 'run_anomaly_detection', 'scheduled__2024-09-11T13:15:00+00:00', '--job-id', '602', '--raw', '--subdir', 'DAGS_FOLDER/Dag-Transaction-Date-in-the-Paste.py', '--cfg-path', '/tmp/tmpzy145pdv']
[2024-09-11T13:20:22.823+0000] {standard_task_runner.py:105} INFO - Job 602: Subtask run_anomaly_detection
[2024-09-11T13:20:26.472+0000] {task_command.py:467} INFO - Running <TaskInstance: detect_transaction_date_anomalies_dag.run_anomaly_detection scheduled__2024-09-11T13:15:00+00:00 [running]> on host 180117ed1726
[2024-09-11T13:20:29.425+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='detect_transaction_date_anomalies_dag' AIRFLOW_CTX_TASK_ID='run_anomaly_detection' AIRFLOW_CTX_EXECUTION_DATE='2024-09-11T13:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-11T13:15:00+00:00'
[2024-09-11T13:20:29.436+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-11T13:20:32.410+0000] {Dag-Transaction-Date-in-the-Paste.py:97} INFO - Inserting 1 detected anomalies
[2024-09-11T13:20:33.932+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-11T13:20:34.356+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-11T13:20:34.358+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=detect_transaction_date_anomalies_dag, task_id=run_anomaly_detection, run_id=scheduled__2024-09-11T13:15:00+00:00, execution_date=20240911T131500, start_date=20240911T132022, end_date=20240911T132034
[2024-09-11T13:20:35.218+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-11T13:20:35.395+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-11T13:20:35.406+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
