[2024-09-13T22:20:35.926+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-13T22:20:37.792+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: correction_Dag_no_NumericValues.Correct_Non_numeric_Quantity scheduled__2024-09-13T22:15:00+00:00 [queued]>
[2024-09-13T22:20:38.149+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: correction_Dag_no_NumericValues.Correct_Non_numeric_Quantity scheduled__2024-09-13T22:15:00+00:00 [queued]>
[2024-09-13T22:20:38.155+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-13T22:20:38.643+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): Correct_Non_numeric_Quantity> on 2024-09-13 22:15:00+00:00
[2024-09-13T22:20:39.802+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'correction_Dag_no_NumericValues', 'Correct_Non_numeric_Quantity', 'scheduled__2024-09-13T22:15:00+00:00', '--job-id', '3808', '--raw', '--subdir', 'DAGS_FOLDER/correction_Dag_no_NumericValues.py', '--cfg-path', '/tmp/tmpwnmz1fmt']
[2024-09-13T22:20:39.857+0000] {standard_task_runner.py:105} INFO - Job 3808: Subtask Correct_Non_numeric_Quantity
[2024-09-13T22:20:39.781+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=78748) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-13T22:20:39.881+0000] {standard_task_runner.py:72} INFO - Started process 78803 to run task
[2024-09-13T22:20:46.041+0000] {task_command.py:467} INFO - Running <TaskInstance: correction_Dag_no_NumericValues.Correct_Non_numeric_Quantity scheduled__2024-09-13T22:15:00+00:00 [running]> on host 7403e816bcf5
[2024-09-13T22:20:47.661+0000] {job.py:229} INFO - Heartbeat recovered after 17.74 seconds
[2024-09-13T22:20:59.364+0000] {job.py:229} INFO - Heartbeat recovered after 11.95 seconds
[2024-09-13T22:21:03.018+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='correction_Dag_no_NumericValues' AIRFLOW_CTX_TASK_ID='Correct_Non_numeric_Quantity' AIRFLOW_CTX_EXECUTION_DATE='2024-09-13T22:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-13T22:15:00+00:00'
[2024-09-13T22:21:04.067+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-13T22:21:28.185+0000] {job.py:229} INFO - Heartbeat recovered after 28.95 seconds
[2024-09-13T22:21:28.304+0000] {logging_mixin.py:190} INFO - Anomalies textuelles corrigées avec succès dans la table Transactions.
[2024-09-13T22:21:28.398+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-13T22:21:39.323+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-13T22:21:39.613+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=correction_Dag_no_NumericValues, task_id=Correct_Non_numeric_Quantity, run_id=scheduled__2024-09-13T22:15:00+00:00, execution_date=20240913T221500, start_date=20240913T222037, end_date=20240913T222139
[2024-09-13T22:21:42.215+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-13T22:21:42.934+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-09-13T22:21:46.436+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-13T22:21:46.502+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
